on:
  push:
  pull_request:

name: make

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install libmlpack-dev
        run: sudo apt-get install libmlpack-dev

      - name: make
        run: make
